### ISSUE TITLE
Locust integration

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn-sandbox/locust-service#1]
The goal is to develop an integration to trigger Locust tests via Keptn.
There are multiple ways to start Locust tests, as far as I know. @adriangonciarz can probably share more details.

Options to start a Locust test:
- Trigger via HTTP call
- Trigger via CLI execution

We need to decide how to start the integration and which option we want to implement first.
The Locust-service needs to be able to trigger a locust test execution upon retrieval of a `sh.keptn.event.test.triggered` event and has to respond with a `sh.keptn.event.test.started` event. Once test execution is finished it has to send a `sh.keptn.event.test.finished` event. Find more details in the spec https://github.com/keptn/spec/blob/master/cloudevents.md#test 

## Usage of the service

In order to get a feeling of how to use the service, here is an example on how to use it.

1. User installs Keptn
1. User adds Locust service to Keptn (via `kubectl`)
1. User creates a project based on shipyard file with a dedicated `test` stage
1. User onboards a service that should be tested
1. User adds Locust test file (e.g., a Python file) via `keptn add-resource` command to Keptn
1. User adds a quality gate (with SLI-provider, SLI-file and SLO-file) - more detail to be added here
1. User sends cloud event to trigger the tests via CLI or API
1. Keptn triggers the tests and evaluates them based on the SLO file

## Definition of done

- [ ] Have a README explaining the usage, installation, and development of the service
- [ ] Have decided for one option how to execute/trigger the Locust tests
- [ ] Have the service implemented, listening to the cloud-events specified above, and sending a cloud-event as specified above

Please feel free to improve and add more details :)

**Comment by adriangonciarz** [comment]
Locust can run in two modes:
1. UI mode
2. Console mode
Console mode now looks a bit more complicated since it will require a "manual" run of locust container in Kubernetes, which is even more complicated when running master/slave architecture, then we'd need to start two deployments with replicas, etc. I'd suggest leaving this for the second run.
Passing test file to the master/slave nodes would also require some more work, for example mounting a volume shared between locust deployments, so I'd leave that one too for now.

In most scenarios, Locust would run in master-slave mode, where we have one master and multiple slave pods. Master and its service (locust-master-service) are always used for test start/stop and getting stats. The address of a master host would be something like `http://locust-master-service:8089` (8089 is the default port), tho it should be configurable.

**UI mode**
UI mode runs as a standalone web application with a simple interface allowing for starting, stopping, and analyzing graphs/response stats. For this run mode, there is no official API, although there is an easy way to trigger and stop tests.
_Triggering tests_
```
curl 'http://locust-master-service:8089/swarm' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' --data-raw 'user_count=$USERS&spawn_rate=$SPAWN_RATE&host=$HOST_URL' 
```
where `USERS, SPAWN_RATE, HOST_URL` are parametrized

_Stopping tests_
```
curl http://locust-master-service:8089/stop
```
Returning 200 HTTP response

_Querying for Stats_
There is also an additional endpoint where tests are reporting stats
```
curl 'http://locust-master-service:8089/stats/requests'
```
Returning JSON response containing among others the status of the test run
```
{
  "state": "running" / "stopped" (alternating), 
...
}
```

**Proposed MVP**
1. We can define Keptn resource storing:
- locust master service host and port
- Test target address (host URL)
- number of users to run
- swarm rate (users per second)
- test run time (???)
2. Locust service can be deployed and awaits test start event
3. Once triggered, Locust Service fetches the resource settings and sends `POST /swarm` to master with configuration
4. Locust Service is waiting a given period of time, possibly with querying `/stats/requests` to make sure locust tests are running 
5. Locust service should send `/stop` request to Locust Master after test run period is over

Let me know what you think

**Comment by grabnerandi** [comment]
Just some input on my side as I have been working on the JMeter Service. Check out the doc for our services and how we use a jmeter.conf.yaml to define different workloads based on the test strategy. [Keptn JMeter Service readme](https://github.com/keptn/keptn/tree/master/jmeter-service)

**Comment by adriangonciarz** [comment]
It would be good to keepconsistency in naming convention. Definitely having profiles under `teststrategy` is a great concept

**Comment by christian-kreuzberger-dtx** [comment]
I wouldn't make it too complicated for end-users.

I've just tried this myself, and you can run locust in headless mode similar to how we run JMeter within the same docker container using this command:
```
locust -f file.py --headless --host=$HOSTNAME_FROM_CLOUDEVENT --users=$USERS --run-time=1m
```

This does not require the end-user to install or configure Locust in the cluster, just the locust-service.

The keptn-service itself can be written within minutes, in fact, I'll create a PR for it.

edit: here it is: https://github.com/keptn-sandbox/locust-service/pull/9

**Comment by christian-kreuzberger-dtx** [comment]
Can we close this one? I think the basic implementation + additional features that we justify to close it :)

**Comment by jetzlstorfer** [comment]
Yes, let's close this one as the service is already working as proven in Keptn installations. 
Let's use new issues for new feature requests (and bugs if any ;) )
